openapi: 3.0.1
info:
  title: Test2
  description: API Definition of Test2
  version: 1.0.0
servers:
- url: http://localhost:8290/second
paths:
  /sample:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
